'use client';
import {useEffect,useState} from 'react';import {RefreshCw,TriangleAlert,ArrowUpRight,ArrowDownRight,Clock3,ShieldAlert} from 'lucide-react';
const fmt=n=>Number.isFinite(n)?n.toLocaleString('en-IN',{maximumFractionDigits:2}):'—';
export default function Dashboard(){const [data,setData]=useState(null),[loading,setLoading]=useState(false),[err,setErr]=useState(''),[interval,setIntervalx]=useState('5m');
 const load=async()=>{setLoading(true);setErr('');try{const r=await fetch('/api/market?interval='+interval,{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error||'Market scan failed');setData(j)}catch(e){setErr(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[interval]);
 const candidates=data?.candidates||[];return <main><header><div><p className="eyebrow">MARKET SCANNER · INTRADAY</p><h1>Index Setup Scanner</h1><p className="muted">Filters out weak index setups and explains the current directional evidence.</p></div><div className="actions"><select value={interval} onChange={e=>setIntervalx(e.target.value)}><option value="5m">5-minute candles</option><option value="15m">15-minute candles</option></select><button onClick={load} disabled={loading}><RefreshCw size={16} className={loading?'spin':''}/> Scan now</button></div></header>
 <section className="scanbar"><div><span className="eyebrow">CURRENT SCAN</span><strong>{candidates.length} candidate{candidates.length===1?'':'s'}</strong><small>{data?'Updated '+new Date(data.updatedAt).toLocaleTimeString():'Loading index data…'}</small></div><div className="scanmeta"><span><i className="dot green"/> Trigger confirmed</span><span><i className="dot amber"/> Watch trigger</span></div></section>
 {err&&<div className="error"><TriangleAlert size={18}/><span>{err}<br/><small>Yahoo Finance index data can be delayed, incomplete, or temporarily unavailable.</small></span></div>}
 {loading&&!data&&<div className="empty">Scanning NIFTY 50, BANK NIFTY, FINNIFTY and MIDCPNIFTY…</div>}
 {data&&candidates.length===0&&<section className="empty"><div className="emptyicon"><Clock3 size={24}/></div><h2>No index setup meets the filter right now</h2><p>The scanner is hiding mixed or weak signals instead of forcing a trade. Scan again after a few candles.</p><button onClick={load} disabled={loading}><RefreshCw size={15}/> Scan again</button></section>}
 <section className="candidates">{candidates.map(item=><IndexCard key={item.id} item={item} interval={interval}/>)}</section>
 {data&&<section className="footnote"><ShieldAlert size={17}/><div><strong>How to use these signals</strong><p>“WATCH” means the directional evidence is aligned but the breakout trigger has not confirmed. “TRIGGERED” means the latest available candle closed beyond the recent range; wait for the candle to finish and verify the live price, liquidity, expiry and option premium in your broker before acting. Target and stop are ATR-based planning levels, not guaranteed outcomes. The strength label is an indicator-confluence score, not a tested win probability.</p><small>{data.hiddenCount} weak/mixed index setup{data.hiddenCount===1?'':'s'} hidden. {data.indexes.filter(x=>x.error).length} index feed error(s).</small></div></section>}
 <footer>Data: Yahoo Finance chart feed · Index spot levels are not option premiums. This scanner does not place orders.</footer></main>}
function IndexCard({item,interval}){const a=item.analysis;const up=a.direction==='UP';const triggered=a.status==='TRIGGERED';return <article className={'candidate '+(up?'up':'down')}><div className="candidateHead"><div><span className="eyebrow">INDEX CANDIDATE</span><h2>{item.name}</h2><div className="spot">{fmt(a.last.close)} <span>spot index</span></div></div><div className="signal"><span className={'signalbadge '+(triggered?'confirmed':'watch')}>{triggered?'TRIGGERED':'WATCH'}</span><strong className={up?'positive':'negative'}>{up?<ArrowUpRight size={18}/>:<ArrowDownRight size={18}/>} {up?'UP BIAS':'DOWN BIAS'}</strong><small>{a.strengthLabel} · {a.strength}/10</small></div></div>
 <div className="levels"><Level label="Breakout trigger" value={a.trigger}/><Level label="Planning target" value={a.target}/><Level label="Invalidation / stop" value={a.stop}/></div>
 <div className="metrics"><Metric label="RSI 14" value={a.rsi.toFixed(1)}/><Metric label="VWAP" value={fmt(a.vwap)}/><Metric label="EMA 9 / 20 / 50" value={(a.ema9>a.ema20&&a.ema20>a.ema50)?'Bullish stack':(a.ema9<a.ema20&&a.ema20<a.ema50)?'Bearish stack':'Mixed'}/><Metric label="Recent range" value={fmt(a.rangeLow)+' – '+fmt(a.rangeHigh)}/></div>
 <div className="reasonGrid"><div><h3><span className="reasonDot"/> Why this move may continue</h3>{a.reasons.length?<ul>{a.reasons.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p className="subtle">No strong directional reasons yet.</p>}</div><div className="cautions"><h3><TriangleAlert size={15}/> Risks / what to watch</h3>{a.cautions.length?<ul>{a.cautions.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p className="subtle">No additional caution flagged by the indicator rules.</p>}</div></div>
 <div className="cardBottom"><span>Timeframe: {interval} · Setup status is based on the latest feed candle.</span><span className="rr">ATR {fmt(a.atr)} · Levels are estimates</span></div></article>}
function Level({label,value}){return <div className="level"><span>{label}</span><strong>{fmt(value)}</strong></div>}function Metric({label,value}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
