function ema(values,p){const k=2/(p+1);let e=values[0]||0;return values.map((v,i)=>i===0?e:(e=v*k+e*(1-k)))}
function rsi(values,p=14){const out=Array(values.length).fill(50);if(values.length<=p)return out;let gains=0,losses=0;for(let i=1;i<=p;i++){const d=values[i]-values[i-1];gains+=Math.max(d,0);losses+=Math.max(-d,0)}let ag=gains/p,al=losses/p;out[p]=al===0?100:100-100/(1+ag/al);for(let i=p+1;i<values.length;i++){const d=values[i]-values[i-1];ag=(ag*(p-1)+Math.max(d,0))/p;al=(al*(p-1)+Math.max(-d,0))/p;out[i]=al===0?100:100-100/(1+ag/al)}return out}
function vwap(rows){let pv=0,vol=0,day='';return rows.map(r=>{const nextDay=new Date(r.time).toISOString().slice(0,10);if(nextDay!==day){pv=0;vol=0;day=nextDay}const typical=(r.high+r.low+r.close)/3;pv+=typical*(r.volume||0);vol+=(r.volume||0);return vol?pv/vol:typical})}
function atr(rows,p=14){const tr=rows.map((r,i)=>i?Math.max(r.high-r.low,Math.abs(r.high-rows[i-1].close),Math.abs(r.low-rows[i-1].close)):r.high-r.low);if(rows.length<p)return tr[tr.length-1]||0;let a=tr.slice(0,p).reduce((x,y)=>x+y,0)/p;for(let i=p;i<tr.length;i++)a=(a*(p-1)+tr[i])/p;return a}
function maxOf(rows,key){return Math.max.apply(null,rows.map(x=>x[key]))}function minOf(rows,key){return Math.min.apply(null,rows.map(x=>x[key]))}
export function analyze(rows){
 if(!rows||rows.length<55)throw new Error('Not enough candles to calculate a stable setup');
 const closes=rows.map(x=>x.close),e9=ema(closes,9),e20=ema(closes,20),e50=ema(closes,50),rs=rsi(closes),vw=vwap(rows),volatility=atr(rows);const i=rows.length-1,last=rows[i],r=rs[i];
 const previous=rows.slice(-13,-1),recent=rows.slice(-30);const rangeHigh=maxOf(previous,'high'),rangeLow=minOf(previous,'low');
 const bullStack=e9[i]>e20[i]&&e20[i]>e50[i],bearStack=e9[i]<e20[i]&&e20[i]<e50[i];
 const aboveVwap=last.close>vw[i],belowVwap=last.close<vw[i];const momentum=last.close-closes[Math.max(0,i-3)];
 const breakoutUp=last.close>rangeHigh,breakoutDown=last.close<rangeLow;
 const priorVolumes=rows.slice(-21,-1).map(x=>x.volume||0),avgVolume=priorVolumes.reduce((a,b)=>a+b,0)/(priorVolumes.length||1);const volumeConfirmed=avgVolume>0&&last.volume>avgVolume*1.25;
 let score=0;const bullReasons=[],bearReasons=[],cautions=[];
 if(bullStack){score+=2;bullReasons.push('EMA 9 > EMA 20 > EMA 50: short- and medium-term trend aligned upward.')}else if(bearStack){score-=2;bearReasons.push('EMA 9 < EMA 20 < EMA 50: short- and medium-term trend aligned downward.')}else cautions.push('EMAs are mixed; trend alignment is not clean.');
 if(aboveVwap){score+=1;bullReasons.push('Price is above today’s session VWAP, showing intraday strength.')}else{score-=1;bearReasons.push('Price is below today’s session VWAP, showing intraday weakness.')}
 if(r>=52&&r<=68){score+=1;bullReasons.push('RSI is positive without being deeply overbought ('+r.toFixed(1)+').')}else if(r<=48&&r>=32){score-=1;bearReasons.push('RSI is negative without being deeply oversold ('+r.toFixed(1)+').')}else if(r>68)cautions.push('RSI is elevated ('+r.toFixed(1)+'); chasing a long breakout may carry pullback risk.');else if(r<32)cautions.push('RSI is very low ('+r.toFixed(1)+'); a bearish move may be stretched.');else cautions.push('RSI is neutral ('+r.toFixed(1)+'); momentum is not decisive.');
 if(momentum>volatility*0.25){score+=1;bullReasons.push('Last three candles show upward price momentum.')}else if(momentum< -volatility*0.25){score-=1;bearReasons.push('Last three candles show downward price momentum.')}
 if(breakoutUp){score+=2;bullReasons.push('Latest candle closed above the previous 12-candle high ('+rangeHigh.toFixed(2)+').')}else if(breakoutDown){score-=2;bearReasons.push('Latest candle closed below the previous 12-candle low ('+rangeLow.toFixed(2)+').')}else cautions.push('No close beyond the recent 12-candle range yet; wait for a trigger.');
 if(volumeConfirmed){if(momentum>=0){score+=1;bullReasons.push('Latest volume is above 1.25× the previous 20-candle average.')}else{score-=1;bearReasons.push('Latest volume is above 1.25× the previous 20-candle average, supporting the downside move.')}}
 let direction=score>=3?'UP':score<=-3?'DOWN':'WAIT';let status='NO TRADE';if(direction!=='WAIT')status=(direction==='UP'&&breakoutUp)||(direction==='DOWN'&&breakoutDown)?'TRIGGERED':'WATCH';
 if(direction==='UP'&&r>68){status='WATCH';cautions.push('Wait for a candle-close confirmation; avoid chasing an extended RSI reading.')}if(direction==='DOWN'&&r<32){status='WATCH';cautions.push('Wait for a candle-close confirmation; avoid chasing an extended RSI reading.')}
 const trigger=direction==='UP'?rangeHigh:direction==='DOWN'?rangeLow:null;const stop=trigger===null?null:(direction==='UP'?trigger-volatility*0.8:trigger+volatility*0.8);const target=trigger===null?null:(direction==='UP'?trigger+volatility*1.5:trigger-volatility*1.5);
 const strength=Math.min(10,Math.abs(score)+2);const strengthLabel=strength>=8?'Strong confluence':strength>=6?'Moderate confluence':'Early / weak';
 return {last,trend:direction==='UP'?'Bullish':direction==='DOWN'?'Bearish':'Mixed',direction,status,score,strength,strengthLabel,rsi:r,ema9:e9[i],ema20:e20[i],ema50:e50[i],vwap:vw[i],atr:volatility,support:minOf(recent,'low'),resistance:maxOf(recent,'high'),rangeHigh,rangeLow,trigger,stop,target,reasons:direction==='UP'?bullReasons:direction==='DOWN'?bearReasons:[],cautions,chart:rows.slice(-80)};
}
