import {multiTimeframeRegime} from '@/lib/regime';
function ema(v,p){const k=2/(p+1);let e=v[0]||0;return v.map((x,i)=>i===0?e:(e=x*k+e*(1-k)))}
function rsi(v,p=14){const o=Array(v.length).fill(50);if(v.length<=p)return o;let g=0,l=0;for(let i=1;i<=p;i++){const d=v[i]-v[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}let ag=g/p,al=l/p;o[p]=al?100-100/(1+ag/al):100;for(let i=p+1;i<v.length;i++){const d=v[i]-v[i-1];ag=(ag*(p-1)+Math.max(d,0))/p;al=(al*(p-1)+Math.max(-d,0))/p;o[i]=al?100-100/(1+ag/al):100}return o}
function atr(rows,p=14){const tr=rows.map((r,i)=>i?Math.max(r.high-r.low,Math.abs(r.high-rows[i-1].close),Math.abs(r.low-rows[i-1].close)):r.high-r.low);let a=tr.slice(0,p).reduce((s,x)=>s+x,0)/Math.min(p,tr.length);for(let i=p;i<tr.length;i++)a=(a*(p-1)+tr[i])/p;return a}
function vwap(rows){let pv=0,vol=0,day='';return rows.map(r=>{const d=new Date(r.time).toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});if(d!==day){pv=0;vol=0;day=d}const tp=(r.high+r.low+r.close)/3;pv+=tp*(r.volume||0);vol+=r.volume||0;return vol?pv/vol:tp})}
const sig=(id,name,direction,trigger,stop,target,reasons,regime,score,conditions={})=>({id,name,direction,trigger,stop,target,reasons,regime,score,conditions,valid:[trigger,stop,target].every(Number.isFinite)});
function trend(rows,reg){const c=rows.map(x=>x.close),e9=ema(c,9),e20=ema(c,20),e50=ema(c,50),a=atr(rows),last=rows.at(-1);const up=e9.at(-1)>e20.at(-1)&&e20.at(-1)>e50.at(-1)&&reg.mid.id==='TREND_UP'&&last.close>e20.at(-1),down=e9.at(-1)<e20.at(-1)&&e20.at(-1)<e50.at(-1)&&reg.mid.id==='TREND_DOWN'&&last.close<e20.at(-1);if(!up&&!down)return null;const d=up?'UP':'DOWN',t=last.close;return sig('TREND_CONTINUATION','Trend continuation',d,t,up?t-a*.9:t+a*.9,up?t+a*1.6:t-a*1.6,['EMA stack and higher timeframe trend agree.','Entry is based on a closed candle.'],reg.mid.id,8,{higherTimeframe:true})}
function breakout(rows,reg){const a=atr(rows),last=rows.at(-1),p=rows.slice(-13,-1),hi=Math.max(...p.map(x=>x.high)),lo=Math.min(...p.map(x=>x.low)),av=rows.slice(-21,-1).reduce((s,x)=>s+(x.volume||0),0)/20,vc=(last.volume||0)>av*1.2;if(last.close>hi&&vc)return sig('RANGE_BREAKOUT','Range breakout','UP',hi,hi-a*.75,hi+a*1.5,['Closed above the 12-candle range high.','Volume confirms the break.'],reg.fast.id,7,{volumeConfirmed:true});if(last.close<lo&&vc)return sig('RANGE_BREAKOUT','Range breakout','DOWN',lo,lo+a*.75,lo-a*1.5,['Closed below the 12-candle range low.','Volume confirms the break.'],reg.fast.id,7,{volumeConfirmed:true});return null}
function retest(rows,reg){if(rows.length<20)return null;const a=atr(rows),c=rows.at(-1),p=rows.slice(-18,-1),hi=Math.max(...p.map(x=>x.high)),lo=Math.min(...p.map(x=>x.low)),up=p.slice(-5).some(x=>x.close>hi),down=p.slice(-5).some(x=>x.close<lo);if(up&&c.low<=hi&&c.close>hi)return sig('BREAKOUT_RETEST','Breakout retest','UP',hi,hi-a*.8,hi+a*1.7,['Prior breakout retested and held.'],reg.mid.id,8,{retest:true});if(down&&c.high>=lo&&c.close<lo)return sig('BREAKOUT_RETEST','Breakout retest','DOWN',lo,lo+a*.8,lo-a*1.7,['Prior breakdown retested and held.'],reg.mid.id,8,{retest:true});return null}
function reversion(rows,reg){if(!['RANGE','LOW_VOLATILITY'].includes(reg.mid.id))return null;const c=rows.map(x=>x.close),r=rsi(c).at(-1),vw=vwap(rows).at(-1),a=atr(rows),last=rows.at(-1);if(r<28&&last.close<vw-a*.35)return sig('VWAP_REVERSION','VWAP mean reversion','UP',last.close,last.close-a*.8,vw,['Range regime with oversold price extension below VWAP.'],reg.mid.id,6,{meanReversion:true});if(r>72&&last.close>vw+a*.35)return sig('VWAP_REVERSION','VWAP mean reversion','DOWN',last.close,last.close+a*.8,vw,['Range regime with overbought price extension above VWAP.'],reg.mid.id,6,{meanReversion:true});return null}
function momentum(rows,reg){const a=atr(rows),last=rows.at(-1),avg=rows.slice(-21,-1).reduce((s,x)=>s+(x.high-x.low),0)/20,body=Math.abs(last.close-last.open),av=rows.slice(-21,-1).reduce((s,x)=>s+(x.volume||0),0)/20;if(body>avg*1.25&&body>a*.7&&(last.volume||0)>av*1.25){const up=last.close>last.open;return sig('MOMENTUM_EXPANSION','Momentum expansion',up?'UP':'DOWN',last.close,up?last.close-a*.8:last.close+a*.8,up?last.close+a*1.5:last.close-a*1.5,['Large impulse candle plus volume expansion.'],reg.fast.id,7,{volumeConfirmed:true})}return null}
export function evaluateStrategies(rows){if(!rows||rows.length<70)return{regime:{},signals:[],selected:null,quality:{state:'NO_TRADE',reasons:['Insufficient candle history.']}};const regime=multiTimeframeRegime(rows),signals=[trend,breakout,retest,reversion,momentum].map(f=>f(rows,regime)).filter(Boolean),dirs=[...new Set(signals.map(x=>x.direction))],up=signals.filter(x=>x.direction==='UP').length,down=signals.filter(x=>x.direction==='DOWN').length,agreement=Math.max(up,down),conflicting=dirs.length>1,aligned=signals.filter(x=>(x.direction==='UP'&&regime.slow.id==='TREND_UP')||(x.direction==='DOWN'&&regime.slow.id==='TREND_DOWN')).length,best=signals.slice().sort((a,b)=>b.score-a.score)[0]||null;const reasons=[];let state='NO_TRADE';if(!signals.length)reasons.push('No independent strategy has a valid setup.');if(conflicting)reasons.push('Strategies disagree on direction.');if(agreement<2&&signals.length)reasons.push('Only one strategy supports the direction.');if(best&&agreement>=2&&!conflicting&&(aligned>0||regime.mid.id==='RANGE'||best.id==='RANGE_BREAKOUT'))state='CANDIDATE';if(best&&agreement>=2&&!conflicting&&best.score>=8&&regime.slow.id!=='HIGH_VOLATILITY')state='ACTIONABLE';return{regime,signals,selected:best,quality:{state,reasons,agreement,conflicting,aligned}}}
